version: "3.9"

networks:
  app-network:
    driver: bridge

services:
  mysql_service:
    container_name: mysql_service
    build: ./mysql
    ports:
      - "6603:3306"
    networks:
      - app-network

  api_service:
    container_name: api_service
    build: ./mysql_api
    ports:
      - "9000:8080"
    depends_on:
      - mysql_service
    networks:
      - app-network

  data_crawling:
    container_name: data_crawling_service
    build: ./data_crawling
    ports:
      - "9002:8081"
    depends_on:
      - mysql_service
    networks:
      - app-network

  # search_webpage:
  #   container_name: webpage_service
  #   build: ./search_webpage
  #   ports:
  #     - "3001:3030"
  #   networks:
  #     - app-network
