version: "3.9"
services:
  mysql_service:
    container_name: mysql_service
    build: ./mysql
    ports:
      - "6603:3306"

  api_service:
    container_name: api_service
    build: ./mysql_api
    ports:
      - "8000:9000"

  data_crawling:
    container_name: data_crawling_service
    build: ./data_crawling
    ports:
      - "8081:9002"

  search_webpage:
    container_name: webpage_service
    build: ./search_webpage
    ports:
      - "3001:8080"
